joint_state_controller:
  type:         joint_state_controller/JointStateController
  publish_rate: &publish_rate 500  # TODO: link this to the control rate

joint_position_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: &robot_joints
    - Joint1
    - Joint2
    - Joint3
    - Joint4
    - Joint5
    - Joint6
